# Plugin created by filoghost. All rights reserved.
# Redistribution of this product is forbidden.

# How often to check mob farms in seconds.
check-interval: 60

broadcast:
  enable: false
  message: '&6[FarmLimiter]&e Removed {amount} entities.'
  # How many entities should be removed at minimum to broadcast the message.
  minimum: 1

rules:
# A global rule active on all the worlds, for groups of 20+ entities.
- entities: all
  exclude: villager
  worlds: all
  distance: 2
  max-amount: 20
# A rule to avoid friendly mob farms, limit the mobs amount to 25.
- entities: pig, cow, sheep, chicken, mushroom cow, rabbit, panda, wolf, turtle, tropical fish, salmon, cod, bee, fox
  worlds: all
  distance: 2
  max-amount: 20
# A rule for spawner grinders, max of 10 mobs of the same type in the same block.
- entities: zombie, skeleton, spider, cave spider, blaze, creeper
  worlds: all
  distance: 4
  max-amount: 20
- entities: villager
  worlds: all
  distance: 2
  max-amount: 15
- entities: turtle
  worlds: all
  distance: 5
  max-amount: 10
- entities: minecart, minecart chest, minecart furnace, minecart hopper
  worlds: all
  distance: 3
  max-amount: 10
- entities: iron golem
  worlds: all
  distance: 5
  max-amount: 8

extra:
  # The rate of mobs that will successfully spawn from a nether portal.
  # Setting to 0% disables mobs spawning from portals.
  portal-spawn-rate: '100%'
  # Whether to exclude tamed entities or not
  exclude-tamed: true
  # Whether to exclude entities with a name tag or not
  exclude-nametagged: false
