mysql:
  enabled: true
  hostname: '[REDACTED]'
  port: [REDACTED]
  username: "[REDACTED]"
  password: "[REDACTED]"
  database: "[REDACTED]"
  playerstable: "[REDACTED]"
settings:
  tag-format-groups:
    1-20: "&8%playerlevel% "
    21-40: "&a%playerlevel% "
    41-60: "&3%playerlevel% "
    61-80: "&6%playerlevel% "
    81-99: "&c%playerlevel% "
    100-100: "&l&d%playerlevel% "
  reset-exp-when-level-up: true
  exp-interval: 1200 #In ticks
  exp-amount-per-interval: 5
  afk-get-exp: false
  exp-per-level:
    0: 0
    1: 50
    2: 150
    3: 300
    4: 500
    5: 750
    6: 1050
    7: 1400
    8: 1800
    9: 2250
    10: 2750
    11: 3300
    12: 3900
    13: 4550
    14: 5250
    15: 6000
    16: 6800
    17: 7650
    18: 8550
    19: 9500
    20: 10500
    21: 11550
    22: 12650
    23: 13800
    24: 15000
    25: 16250
    26: 17550
    27: 18900
    28: 20300
    29: 21750
    30: 23250
    31: 24800
    32: 26400
    33: 28050
    34: 29750
    35: 31500
    36: 33300
    37: 35150
    38: 37050
    39: 39000
    40: 41000
    41: 43050
    42: 45150
    43: 47300
    44: 49500
    45: 51750
    46: 54050
    47: 56400
    48: 58800
    49: 61250
    50: 63750
    51: 66300
    52: 68900
    53: 71550
    54: 74250
    55: 77000
    56: 79800
    57: 82650
    58: 85550
    59: 88500
    60: 91500
    61: 94550
    62: 97650
    63: 100800
    64: 104000
    65: 107250
    66: 110550
    67: 113900
    68: 117300
    69: 120750
    70: 124250
    71: 127800
    72: 131400
    73: 135050
    74: 138750
    75: 142500
    76: 146300
    77: 150150
    78: 154050
    79: 158000
    80: 162000
    81: 166050
    82: 170150
    83: 174300
    84: 178500
    85: 182750
    86: 187050
    87: 191400
    88: 195800
    89: 200250
    90: 204750
    91: 209300
    92: 213900
    93: 218550
    94: 223250
    95: 228000
    96: 232800
    97: 237650
    98: 242550
    99: 247500
    100: 252500
  commands-to-execute-when-level-up:
    - ""
