#  _____            _____                         _   _          
# |  __ \          / ____|                       | | (_)         
# | |__) | __ ___ | |     ___  ___ _ __ ___   ___| |_ _  ___ ___ 
# |  ___/ '__/ _ \| |    / _ \/ __| '_ ` _ \ / _ \ __| |/ __/ __|
# | |   | | | (_) | |___| (_) \__ \ | | | | |  __/ |_| | (__\__ \
# |_|   |_|  \___/ \_____\___/|___/_| |_| |_|\___|\__|_|\___|___/ COPYRIGHT Â©
#
# Thank you for purchasing ProCosmetics! 
#

General:
  Disabled-Worlds:
    - world_no_cosmetics
    - world_nether

  #Stores your last used cosmetics and next time you login to the server they will automatically be equipped.
  Restore-Cosmetics: true

  #Change this based on your permission plugin! This command will run once a player purchases a cosmetic.
  Permission-Add-Command: "lp user (player) permission set (permission)"

  #The name-tag above the entities head for Mounts & Pets!
  Entity-Owner-Displayname: "&b(player)'s &7(cosmetic)"

  Tossing-Items:
    Pets: true
    Mounts: true

  #This will disable the 2D menu and enable the 3D menu!
  Use-3D-Menu: false

  Gadget-Slot: 6

  Cosmetic-Menu:
    Title: "Cosmetic Menu"
    Size: 54
    Fill-Empty-Slots: false
    Give-On-Join: false
    Give-On-World-Change: false

    Material: CHEST
    Amount: 0
    Slot: 0
    Displayname: "&aCosmetic Menu &7(Right Click)"
    Lore:
      - "&7Right-click to open the Cosmetic menu."

  Fill-Empty-Slots:
    Material: GRAY_STAINED_GLASS_PANE
    Amount: 1

  Unequip-All-Cosmetics:
    Material: BARRIER
    Amount: 1
    Slot: 4
    Displayname: "&cUnequip All Cosmetics"
    Lore:
      - ""
      - "&7Right-click to unequip your current cosmetics!"

  #Set amount to 0 if you want to disable this feature.
  Current-Coins:
    Material: SUNFLOWER
    Data: 0
    Amount: 1
    Slot: 22
    Displayname: "&bYou have &e$(coins)!"
    Lore:
      - ""
      - "&7This is your account balance. Do /bal"
  Go-Back:
    Material: RED_BED
    Amount: 1
    Slot: 4
    Displayname: "&aGo back"
    Lore: []

  Purchase:
    Title: "Confirm Purchase"
    Size: 27
    Fill-Empty-Slots: true

    Accept:
      Material: LIME_TERRACOTTA
      Amount: 1
      Slot: 16
      Displayname: "&aAccept Purchase"
      Lore:
        - ""
        - "&7Click to purchase!"

    Deny:
      Material: RED_TERRACOTTA
      Amount: 1
      Slot: 10
      Displayname: "&cDeny Purchase"
      Lore:
        - ""
        - "&7Click to cancel!"

  Cosmetic-Not-Unlocked-Description:
    - "(cosmeticDescription)"
    - "&7Purchase for &b$(cost)!"

Anti-Lag:
  Use: false
  Minimum-TPS: 18.0
  Unequip-Cosmetics: true
  Disable-Usage: true

MySQL:
  Use: false
  Host: localhost
  Port: 3306
  Database: ProCosmetics
  Table: ProCosmeticsData
  User: [REDACTED]
  Password: [REDACTED]

Economy:
  #By disabling vault support the plugin will use its own separate currency system.
  Use-Vault: true
  Coin-Party-Bomb-Amount: 20

#World Guard
Blacklisted-Regions:
  Unequip:
    Arrow-Effect: false
    Balloon: true
    Banner: true
    Death-Effect: false
    Emote: true
    Gadget: true
    Miniature: true
    Morph: true
    Mount: true
    Music: true
    Particle-Effect: false
    Pet: true

  Regions:
    - "Region1"
    - "Region2"